from typing import Protocol
import numpy as np


class MotionModel(Protocol):
    def propagate(self, x: np.ndarray, dt: float) -> np.ndarray: ...
    def F(self, x: np.ndarray, dt: float) -> np.ndarray: ...
    def Q(self, dt: float, **params) -> np.ndarray: ...


class MeasurementModel(Protocol):
    def h(self, x: np.ndarray) -> np.ndarray: ...
    def H(self, x: np.ndarray) -> np.ndarray: ...
    def R(self, **params) -> np.ndarray: ...


class Filter(Protocol):
    x: np.ndarray
    P: np.ndarray

    def predict(self, dt: float) -> None: ...
    def update(self, z: np.ndarray) -> None: ...
